what is numpy?
numpy= numerical python

it is used for:

fast mathematical operation
working with large datasets
scientific computing

In [2]:
import numpy as np

python list as numpy array

numbers=[1,2,3,4]
data=[1,"hello",3.5]

-can store diffrent datatypes
-strored in scattared memory
-slower for larger calculations

numpy array:
arr=np. array{[1,2,3,4]}

-store same datatype
-store in continuous memory
-much faster
-suppored mathematical operations


memory differece:

python list                                         numpy array
------------                                        --------------
-flexible                                         -fixed data type
-slower                                            - faster
-different types allowed                          - same type only
-memory scattered                                  -memory is continuous

In [4]:
#ndarray- (N-dimensional arry)
arr=np.array([1,2,3,4])
print(arr * 2)

#normal list
numbers=[1,2,3,4,]
print(numbers * 2)

[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]


In [6]:
arr=np.array([10,20,30])
print(arr)

#2D example

arr1=np.array([[1,2,3],
             [4,5,6]])
print(arr1)

[10 20 30]
[[1 2 3]
 [4 5 6]]


In [ ]:
#np.zeros
#creates array filled with zeros

arr=np.zeros(5)

arr=np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


In [3]:
#np . arange
#similar to range function

np.arange(0,10,2)

#(start,stop,step)

array([0, 2, 4, 6, 8])

In [14]:
#np.linspace
#creates evenly spaced numbers

print(np.linspace(0,10,5))

#(start,stop,number_of_values)

#logspace
#evenly spaced log values


[ 0.   2.5  5.   7.5 10. ]


In [9]:
#np.full

np.full((2,3),7) # one dimentional

#(space,full_value,[dtype]here dtype is optional)
print(np.full((2,2),5,float))

print(np.full((3,3),True))

print(np.full((3,2),"NA")) #used when marking missing categorical values

#creates an array filled with any specific value 
#useful for initialization

[[5. 5.]
 [5. 5.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[['NA' 'NA']
 ['NA' 'NA']
 ['NA' 'NA']]


In [15]:
#if all 5 students get a bonus marks of 2

marks=np.array([80,75,90,85,88])
bonus=np.full(marks.shape,2)

final_marks=marks+bonus
print(final_marks)

[82 77 92 87 90]


In [ ]:
#np.eye
#creates identity matrix (diagonal=1)

print(np.eye(3))

print(np.diag([1,2,3]))
#create diagnal matrix

np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#np.random
#creates an array of random numbers between 0 and 1

print(np.random.rand(3))

print(np.random.rand(2,3))

print(np.random.randint(1,10,5))

#creates 5 random numbers between 1 and 9

#random choice
colors=["red","blue","orange","green"]
print(np.random.choice(colors))

#multiple selection
print(np.random.choice(colors,size=5))

[0.27585131 0.59315814 0.5904117 ]
[[0.45181553 0.12816525 0.23122744]
 [0.88813018 0.70506591 0.60419576]]
[2 9 3 1 1]
red
['blue' 'green' 'orange' 'green' 'blue']


#brodcasting

#broadcasting allows operations between arrays of different shapes

#broad casting eules-
two arrays are compatible if:

1. they have same shape
   or

2. one of them is 1
   or

3, smaller array can stretch to match larger

In [16]:
arr=np.array([1,2,3])

print(arr+5)

[6 7 8]


In [17]:
#broadcasting 1D with 2D

arr=np.array([[1,2,3],
             [4,5,6]])

b=np.array([10,20,30])

print(arr+b)

[[11 22 33]
 [14 25 36]]


In [ ]:
a=np.array([[1,2,3],
           [4,5,6]])
b=np.array([1,2])
print(a+b)

#broadcasting fails


[[2 4]
 [5 7]]


In [19]:
#column braodcasting

arr=np.array([[1,2,3],
              [4,5,6]])

col=np.array([[10],
            [20]])
print(arr+col)

[[11 12 13]
 [24 25 26]]


#vectorization
doing operations on entire array at once instead of using loops

vectiorization makes it:
-faster
-cleaner code
-less memory usage


In [21]:
#square all numbers
arr=np.array([1,2,3,4])
print(arr**2)

[ 1  4  9 16]


In [22]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)

[5 7 9]


In [23]:
#conditional vectorization

arr=np.array([10,20,30,40])
print(arr>25)

[False False  True  True]


In [24]:
#using condition to modify values

arr[arr>25]=100
print(arr)

[ 10  20 100 100]


In [25]:
#using where

np.where(arr>25,1,0)

array([0, 0, 1, 1])

In [27]:
#mathematical operations

arr=np.array([1,2,3,4])

print(np.sort(arr))
print(np.sqrt(arr))
print(np.log(arr))
print(np.sin(arr))

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [28]:
#braodcasting +vectorization together

arr=np.array([[1,2,3],
              [4,5,6]])

mean=np.array([2,3,4])

print(arr-mean)

#broadcasting handles shapes, vectorization handles operation

[[-1 -1 -1]
 [ 2  2  2]]
